### PR TITLE
Fix "VirtualView cannot be null here" on Android when `OnLayout` is fired after the handler is disconnected

### PR DESCRIPTION
**Pull request by romerotg**
This is a fix to the issue #91

### CODE REVIEW

**Comment by Nilotaviano** [comment]
FINALLY! I was at my wits end. Looking forward for this to be merged.

**Comment by Jabbah76** [comment]
@romerotg Do you maybe have an estimate when we can expect a new version with this fix?

**Comment by romerotg** [comment]
> @romerotg Do you maybe have an estimate when we can expect a new version with this fix?

@Jabbah76 I don't know. I'm not the maintainer of the repository

**Comment by borrmann** [comment]
We really need this too.
@romerotg Do you have an idea whether there is some way to use your fix in the meantime/ to add some simplified fix (try catch in a overridden handler or so)?

**Comment by romerotg** [comment]
> We really need this too. @romerotg Do you have an idea whether there is some way to use your fix in the meantime/ to add some simplified fix (try catch in a overridden handler or so)?

@borrmann  while the fix isn't merged to the repository, I just imported my fork with the fix (https://github.com/romerotg/Mopups/) directly into the project. Once the new release is out I'll remove the reference and re-add the nuget reference

**Comment by Mysame** [comment]
I can confirm this pull request fixes all of the crashes I had using Mopups. Thank you very much.

**Review by LuckyDucko — APPROVED** [review]
Excellent work here, really do appreciate this.

**Pull request merged**
