### PR TITLE
Hack to respect safe areas

### PR DESCRIPTION
**Pull request by AswinPG**
The LayoutChildren method does not work. This is a little hack to make the popup render inside safe area

### CODE REVIEW

**Comment by tranb3r** [comment]
It looks like HasSystemPadding is now ignored and SystemPadding is always used.
Is HasSystemPadding obsolete ?

**Comment by LuckyDucko** [comment]
For the time being yes, this will be eventually reverted to be fixed however

**Comment by AswinPG** [comment]
I never actually used HasSystemPadding property before, so I didn't think of adding it. Simply adding an if condition bfore applying the padding can make it work. I'll add a PR
@tranb3r @LuckyDucko

**Comment by AswinPG** [comment]
I am really sorry @LuckyDucko I made a mistake and merged the changes instead of creating a PR :|
Didn't know that I had write access.. 
Sorryyy... What should be done now ..?

**Comment by LuckyDucko** [comment]
@AswinPG thats all good, no worries ahaha, i am the only one able to release a nuget. Give me a litte time to see whats changed

**Pull request merged**
