### PR TITLE
Fix: Exception "MauiContext should have been set on parent" when removing a child from its parent layout on iOS

### PR DESCRIPTION
**Pull request by troy-ob**
We experienced the same issue as described in issue #97 in our project and the suggested solution fixed it for us.

### CODE REVIEW

**Comment by vecalion** [comment]
@LuckyDucko, I wonder if this can be merged? https://github.com/LuckyDucko/Mopups/issues/128

**Comment by indyjason79** [comment]
This would be awesome to get merged in ASAP. We have a release in 2 weeks and have a need to remove UI elements from the popup and this is blocking.

**Comment by robin-schroeder-merc** [comment]
I am still experiencing this error with Mopups v1.3.2. (.Net 8.0.402) Any work arounds? It seems to only happen when I trigger and dismiss a Syncfusion picker immediately before a Mopups popup. I think the SFPicker is technically a popup as well and I am wondering if they are using the same stack or something.

**Comment by robin-schroeder-merc** [comment]
Turns out I needed to wrap the push for the popup in an MainThread.BeginInvokeOnMainThread. Hope this helps someone.

**Pull request merged**
