### PR TITLE
Fixes android accessibility handling

### PR DESCRIPTION
**Pull request by IeuanWalker**
#93 

Things changed in this PR -

- Removed `AndroidTalkbackAccessibilityWorkaround`, this was left over from the Xamarin.Forms implementation and wasn't actully being used in the Maui version 
- Added `DisableAndroidAccessibilityHandling`
    - I don't imagine a lot of people needing to use this, but just prevents people adding workarounds like the one mentioned in the comments of the linked issue
- Main fix to the linked issue is keeping a list of the android views that the accessibility handling was ran against to disable the focusability  of the elements. It then uses that list to re-enable the focusability

### CODE REVIEW

**Comment by LuckyDucko** [comment]
@IeuanWalker great stuff! Thanks for the PR.

Just wanted to leave a comment, i am out on my honeymoon in Japan until the end of the month, if i don't start merging PR's in December bump this and I'll jump on it!

**Comment by troy-ob** [comment]
Hi

thanks for the fix @IeuanWalker  and thanks for the merge @LuckyDucko :) 

Do you have any plans for a new NuGet package with the latest changes?

**Comment by LuckyDucko** [comment]
Yeah i just need to pay a bit more attention to the last PR i need to merge, then i'll do a touch of testing and try to fire something out.

Getting held up by putting up holiday lights, but lets all hope for a christmas miracle and a speedy release ;)

**Comment by troy-ob** [comment]
Heya @LuckyDucko 

I hope you had a nice Christmas and a good start to 2024 :) 

Just wanted to ask again if you have an ETA of a new release?

**Pull request merged**
